server:
  forward-headers-strategy: framework

management:
  endpoint:
    health:
      show-details: never

spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:validate}
    show-sql: false
    open-in-view: false

